# Generated by Django 4.2.27 on 2026-01-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
