# Generated by Django 4.2.27 on 2026-01-02 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
        ('accounts', '0002_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectusermapping',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
